import type { Metadata } from "next";
import Providers from "./Providers";
import Navbar from "@/components/layout/Navbar";
import localFont from "next/font/local";
import SmoothScroll from "@/components/layout/SmoothScroll";
import CustomCursor from "@/components/CustomCursor";
import Navigation from "@/components/Navigation";
import "./globals.css";

const YekanBakhFont = localFont({
  src: [
    {
      path: "./fonts/YekanBakh/YekanBakh-Thin.woff2",
      weight: "200",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-Light.woff2",
      weight: "300",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-Bold.woff2",
      weight: "700",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "./fonts/YekanBakh/YekanBakh-Black.woff2",
      weight: "900",
    },
  ],
});

const KalamehFont = localFont({
  src: [
    {
      path: "./fonts/Kalameh/KalamehWebFaNum-Thin.woff2",
      weight: "200",
    },
    { path: "./fonts/Kalameh/KalamehWebFaNum-Regular.woff2", weight: "400" },
    {
      path: "./fonts/Kalameh/KalamehWebFaNum-Bold.woff2",
      weight: "700",
    },
    {
      path: "./fonts/Kalameh/KalamehWebFaNum-Black.woff2",
      weight: "900",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${KalamehFont.className}`}>
      <body className="bg-[##faf7f6] dark:bg-[#161616] transition-colors overflow-x-hidden">
        <CustomCursor />
        <Providers>
          <Navbar />
          <SmoothScroll>{children}</SmoothScroll>
          <Navigation />
        </Providers>
      </body>
    </html>
  );
}
